disabled virtualhost script sample file creation

diff --git a/scripts/virtualhost b/scripts/virtualhost
--- a/scripts/virtualhost
+++ b/scripts/virtualhost
@@ -72,13 +72,13 @@ if [ "$action" == 'create' ]
 			### give permission to root dir
 			chmod -R 777 $rootDir
 			### write test file in the new domain dir
-			if ! echo "<?php echo phpinfo(); ?>" > $rootDir/phpinfo.php
-			then
-				echo $"ERROR: Not able to write in file $rootDir/phpinfo.php. Please check permissions"
-				exit;
-			else
-				echo $"Added content to $rootDir/phpinfo.php"
-			fi
+			# if ! echo "<?php echo phpinfo(); ?>" > $rootDir/phpinfo.php
+			# then
+			# 	echo $"ERROR: Not able to write in file $rootDir/phpinfo.php. Please check permissions"
+			# 	exit;
+			# else
+			# 	echo $"Added content to $rootDir/phpinfo.php"
+			# fi
 		fi
 
 		### create virtual host rules file
